version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: The raw data of Greenweez containing costs relating to shipping, sales, and products
    tables: 
      - name: adwords
        identifier: raw_gz_adwords
      - name: bing
        identifier: raw_gz_bing
      - name: criteo
        identifier: raw_gz_criteo
      - name: facebook
        identifier: raw_gz_facebook
      - name: product
        identifier: raw_gz_product
        description: List of products by ID and their cost
        columns:
          - name: products_id
            description: The product's unique ID, primary key
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: The cost of each product

      - name: sales
        identifier: raw_gz_sales
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
        description: Sales of Greenweez, one row per `products_id` found in each `orders_id`
        columns:
          - name: date_date
            description: Date of purchase
          - name: orders_id
            description: ID of the order
          - name: products_id
            description: ID of the products
          - name: revenue
            description: Income from purchase
          - name: quantity
            description: Total quantity purchased
        

      - name: ship
        identifier: raw_gz_ship
        description: Shipping fee, logistics cost, and shipping fee per order ID
        columns:
          - name: orders_id
            description: ID of the order
            tests:
              - not_null
              - unique
          - name: shipping_fee
            description: The cost of shipping the product to the customer
          - name: logcost
            description: The logistical cost of shipping the product
          - name: ship_cost
            description: The cost of shipping the product to the business

